version: '3'

services:
  server:
    image: voyager/server
    container_name: voyager-server
    build:
      context: ./services/server/setup
      dockerfile: Dockerfile
    env_file:
      - services/config.env
      - services/secrets.env
    ports: #host:container
      - "8000:8000"
    volumes:
      - .:/app
